name: HawkScan Example
on:
  workflow_dispatch:

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
#      - name: Download and run JavaSpringVulny release jar
#        run: |
#          curl -Ls https://github.com/kaakaww/javaspringvulny/releases/download/0.2.0/java-spring-vuly-0.2.0.jar -o ./java-spring-vuly-0.2.0.jar
#          java -jar ./java-spring-vuly-0.2.0.jar &
      - name: Build and run JavaSpringVulny (slower)
        run: |
          ./gradlew build
          ./gradlew bootRun &
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          APP_ID: ${{ secrets.appId }}
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
      - name: Upload SARIF file - No GHAS
        uses: actions/upload-artifact@v4
        with:
          name: StackHawk_Report_${{ github.run_id }}
          path: stackhawk.sarif
          if-no-files-found: error
      - name: Upload results to MSDO
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          existingFilename: stackhawk.sarif
